### ISSUE TITLE
Related work

### ISSUE THREAD

**Issue by polytypic** [ndmitchell/uniplate#16]
The [MLtonLib generics library](https://github.com/MLton/mltonlib/tree/master/com/ssh/generic/unstable) has a basic [Uniplate inspired generic](https://github.com/MLton/mltonlib/blob/master/com/ssh/generic/unstable/public/value/uniplate.sig).

More recently I've also made another experimental [Uniplate inspired generic in F#](http://polytypic.github.io/Infers/Infers.Toys.html#def:module Infers.Toys.Elems) using my experimental [Infers](https://github.com/polytypic/Infers) library for deriving F# values from their types.

**Comment by ndmitchell** [comment]
Thanks! I'm not working on Uniplate at the moment, but plan to circle back round to it in a bit, so I'll update the docs then.

**Comment by ndmitchell** [comment]
Thanks, for the links. It took a while to get back to it, but both are in the README now!
