### ISSUE TITLE
Working with Biplate and Vector does not behave in a similar way as list

### ISSUE THREAD

**Issue by soupi** [ndmitchell/uniplate#24]
Hey, thanks for this lovely package.

I tried using uniplate with vector but got an unexpected behaviour. It seems that transformBi does not apply a function over vectors the same way it would work over a list:

```
stack ghci --package uniplate --package vector
Configuring GHCi with the following packages: 
GHCi, version 8.2.2: http://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from /home/gilm/.ghci
Loaded GHCi configuration from /tmp/haskell-stack-ghci/2a3bbd58/ghci-script
λ> import Data.Generics.Uniplate.Data
λ> import qualified Data.Vector as V
λ> transformBi not [False]
[True]
λ> transformBi not (V.singleton False)
[False]
```

Any ideas to what's going on?

Thanks!

**Comment by ndmitchell** [comment]
The reason will be that the `Data` instances for `Vector` don't expose access to the internal elements. `Uniplate.Data` just uses the `Data` instance, the same one the `syb` package uses, so I assume that `syb` won't work either. Solution can be to write a custom Uniplate instance for `Vector`, or to wrap the `Vector` in a newtype. Looking at the source, https://hackage.haskell.org/package/vector-0.12.0.2/docs/src/Data.Vector.html#line-252, it does indeed seem that Vector doesn't really implement most of the `Data` methods.

**Comment by soupi** [comment]
That makes sense. Thank you!

**Comment by soupi** [comment]
I've just found out that this issue has been fixed in vector's master branch ([PR](https://github.com/haskell/vector/pull/205)) but not yet released.
I have verified this works:

```
λ> transformBi not (V.singleton False)
[True]
```

This issue can probably be closed!

**Comment by ndmitchell** [comment]
Thanks for tracking it down!
