### ISSUE TITLE
Broken link in readme

### ISSUE THREAD

**Issue by googleson78** [ndmitchell/uniplate#26]
The "project website" link in [README.MD](https://github.com/ndmitchell/uniplate/blob/fc77daace62bbfdc3842022b0bbe9ac107510b28/README.md) (current master - fc77daace62bbfdc3842022b0bbe9ac107510b28) is broken.

Did it move somewhere?

**Comment by ndmitchell** [comment]
Yep, I redid my website - you can find the links at https://ndmitchell.com/#uniplate_30_sep_2007. I updated the readme - thanks for letting me know.
