### ISSUE TITLE
Doesn't compile against ghc 901

### ISSUE THREAD

**Issue by expipiplus1** [ndmitchell/uniplate#31]
```
Data/Generics/Uniplate/Internal/Utils.hs:26:17: error:
    Module ‘GHC.Exts’ does not export ‘SpecConstrAnnotation(..)’
   |
26 | import GHC.Exts(SpecConstrAnnotation(..))
   |                 ^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by ndmitchell** [comment]
Thanks for the heads up!

Apparently I should be using https://hackage.haskell.org/package/ghc-prim-0.6.1/docs/GHC-Types.html#t:SPEC - but that adds a dependency on ghc-prim which is a bit sad. https://gitlab.haskell.org/ghc/ghc/-/issues/13681 is the issue that removed it. I'll await confirmation from the GHC team before fixing it.

**Comment by expipiplus1** [comment]
Cool, thanks!

**Comment by ndmitchell** [comment]
I believe this should now work. I'll make a release later tonight.

**Comment by ndmitchell** [comment]
1.6.13 now out, let me know if you still have issues.

**Comment by expipiplus1** [comment]
Thanks!
