### ISSUE TITLE
Documentation problems

### ISSUE THREAD

**Issue by erikd** [ndmitchell/uniplate#6]
At least one correction:
- The `LANGUAGE` pragma seems to be `DeriveDataTypeable` not `DerivingDataTypeable`.

The other problem is that I can't seem to get the first example to work:

``` haskell
{-# LANGUAGE DeriveDataTypeable #-}
module Expr where

import Data.Generics.Uniplate.Data

data Expr
    = Val Int
    | Add Expr Expr
    | Sub Expr Expr
    | Div Expr Expr
    | Mul Expr Expr
    | Neg Expr
    deriving (Show, Eq, Data, Typeable)
```

results in:

```
Not in scope: type constructor or class ‘Data’
Not in scope: type constructor or class ‘Typeable’
```

Tried GHC 7.6.3, 7.8.4 and 7.10.2. Clues?

**Comment by erikd** [comment]
Seems the examples also needs:

```haskell
import Data.Data
import Data.Typeable
```

**Comment by ndmitchell** [comment]
Sorry for the hassle - that's annoying. Importing just `Data.Data` will do, since it reexports `Data.Typeable`. The library really needs a tidy up to point at the github website instead of my old haskell.org one. I've updated the GitHub readme and will do the release later on.

**Comment by erikd** [comment]
Thanks Neil!

**Comment by ndmitchell** [comment]
I think these issues are all now fixed.
