### ISSUE TITLE
Descend for more than two types

### ISSUE THREAD

**Issue by minad** [ndmitchell/uniplate#7]
Hi Neil,

I haven't found a mailing list where I could ask a question about uniplate and hope it is ok, if I ask here.

Is there are possibility to do a descend which can map more than one type in the same pass? Something like

~~~ haskell
descend :: (on -> on) -> on -> on
descendBi :: (to -> to) -> from -> from
descendTri :: (a -> a) -> (b -> b) -> from -> from
...
~~~

These functions can be written by hand for a given data type, but I am just wondering if there is a generic solution for that.

Best,
Daniel

**Comment by ndmitchell** [comment]
Hi Daniel - very happy to take questions on GitHub for any of my projects.

There is no descendTri - and it's impossible to implement on top of the underlying uniplate operation, which all other operations are based upon. You can do two `descendBi`s one after another, which is usually how the operation is done.

**Comment by minad** [comment]
Thank you for your answer! 

Ok, in the case with descendBi/descendTri I agree. However I am using a reader monad to pass some local state (should have written that in the beginning), then descendTriM cannot be implemented in terms of descendBiMs because the state is passed down and the order matters.  Probably this cannot be done then using uniplate,but has to be written by hand? This is how I am currently doing it, however the more I learn about Haskell, the more smarter libraries (like yours) I discover :)

**Comment by ndmitchell** [comment]
Yeah, if the order matters, you need to use something else. There are other generics frameworks, for example SYB would allow that.

**Comment by minad** [comment]
Great thank you! extM should do it :)
